### ISSUE TITLE
Segmentation Fault in CyGutz

### ISSUE THREAD

**Issue by henhans** [yaoyongxin/CyGutz#1]
Dear Yongxin,

I have successfully compiled the code, but I met the segmentation fault error while executing CyGutz. Please see the message below:

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
CyGutz             000000000051394D  Unknown               Unknown  Unknown
libpthread-2.23.s  00007F6E894BB390  Unknown               Unknown  Unknown
CyGutz             0000000000477210  bandstru_mp_rotat         292  BANDSTRU.f90
libiomp5.so        00007F6E88EFF413  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00007F6E88ECF60D  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00007F6E88EA7EE8  __kmpc_fork_call      Unknown  Unknown
CyGutz             0000000000476846  bandstru_mp_rotat         269  BANDSTRU.f90
CyGutz             000000000040D477  MAIN__                     95  CYGUTZ.f90
CyGutz             000000000040D32E  Unknown               Unknown  Unknown
libc-2.23.so       00007F6E88AB0830  __libc_start_main     Unknown  Unknown
CyGutz             000000000040D229  Unknown               Unknown  Unknown

The message seems to involve openmp. I have tested it on two computer (8GB and 16GB mem) with intel-2016 and intel-2017. They both show the same error message. I am wondering if you know the solution for this problem?

Thank you.
Tsung-Han

**Comment by yaoyongxin** [comment]
Hi, Tsung-Han:

    Is it the newest version? Did you compile it on somewhere in rupc
clusters? I will have Viktor about the password and get access to it.
Thanks.

    Regards, Yongxin

**Comment by henhans** [comment]
Dear Yongxin,

The code works fine on the cluster. I am trying to install it on my Desktop to test the Pu system, but I could not find out how to solve this error message. It looks like it is related to stack memory.

Best, Tsung-Han

**Comment by henhans** [comment]
Also, I am installing the new version.
Best, Tsung-Han

**Comment by yaoyongxin** [comment]
I think this issue has been solved.
