### ISSUE TITLE
Segmentation fault in Cygutz

### ISSUE THREAD

**Issue by vamshimohank** [yaoyongxin/CyGutz#2]
Dear Yongxin,

I have been trying to get the code running for the band insulating compounds Ba2YIrO6 (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.93.035129) and NaIrO3 (http://iopscience.iop.org/article/10.1209/0295-5075/101/27003/meta) compounds.  I come across Segmentation fault error at the CyGutz step. If I understand correctly, the correlated space automatically chosen by the code when specifying Ir d as the correlated orbitals, turns out to be too large (40 electrons for Ba2YIrO6, I guess this is because of the strong hybridisation of the Ir d orbitals with the O 2p orbitals ), and hence there seems to be some memory issues.  Have you ever came across such issues? and if so how does one solve it? In some sense is there a way to specify the orbital numbers just as it is done in the lda+dmft code. 

Thanks and Regards
Vamshi

**Comment by yaoyongxin** [comment]
We have email communications I think the problem has been addressed. The remaining question seems the construction of Wannier functions and the Wannier Hamiltonian. The current code (Wien2K+G) cannot handle it as of now however. But we are working on the comsuite from the DOE Center for Computational Material Spectroscopy and Design at brookhaven national lab. In that new software, CyGutz directly works on generic Hubbard model downfolded with wannier90. That will directly address your question. We should be able to release that very soon.
